export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  INVALID_PLAN_STATUS: "INVALID_PLAN_STATUS",
  PLAN_LOCKED: "PLAN_LOCKED",
  PLAN_PENDING_CORRECTION: "PLAN_PENDING_CORRECTION",
  CORRECTION_ITEMS_REQUIRED: "CORRECTION_ITEMS_REQUIRED",
  CORRECTION_ITEMS_UNRESOLVED: "CORRECTION_ITEMS_UNRESOLVED",
  CORRECTION_ITEM_NOT_FOUND: "CORRECTION_ITEM_NOT_FOUND",
  NOT_PLAN_OWNER: "NOT_PLAN_OWNER"
} as const;
export type ErrorCode = keyof typeof ERROR_CODES;
