export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  CORRECTION_ITEM_NOT_FOUND: "CORRECTION_ITEM_NOT_FOUND",
  INVALID_PLAN_STATUS: "INVALID_PLAN_STATUS",
  PLAN_FIELDS_LOCKED: "PLAN_FIELDS_LOCKED",
  CORRECTION_ITEMS_OPEN: "CORRECTION_ITEMS_OPEN",
  CORRECTION_REQUIREMENT_MISSING: "CORRECTION_REQUIREMENT_MISSING",
  CORRECTION_DEADLINE_MISSING: "CORRECTION_DEADLINE_MISSING",
  CORRECTION_RESOLUTION_MISSING: "CORRECTION_RESOLUTION_MISSING"
} as const;
